### ISSUE TITLE
[Feature] Development Skin Packs Functionality

### ISSUE THREAD

**Issue by Gekocaretaker1** [solvedDev/bridge.#119]
When I looked through the com.mojang folder, I found a folder called development_skin_packs. And I have found addons that uses this feature. Is it possible for you to add support for these.

**Comment by solvedDev** [comment]
Thanks for your suggestion! :) However, I don't think that it's worth spending my time on this specific feature because...
a) I don't think that's a thing bridge. should do.
b) I think it's not something which is useful for many people.

I am open for a discussion about this here or on the Discord server though.
