### ISSUE TITLE
All addons seemingly use the scripting engine

### ISSUE THREAD

**Issue by Mechanical-Games** [solvedDev/bridge.#17]
**The Problem**
All addons seemingly use the Scripting Engine. I accounted this when testing my addon on mobile devices. I made a plain addon with just the manifest and it still set it required to run scripts.

**Steps to Reproduce**

1. Make a plain addon with literally just the `manifest.json`
2. Package in bridge.
3. Run on a platform which cannot run Scripts i.e iOS

**Screenshots**
![image](https://user-images.githubusercontent.com/49130644/61073624-b2096100-a40d-11e9-8f5c-830d510aa9f6.png)
![image](https://user-images.githubusercontent.com/49130644/61073696-e715b380-a40d-11e9-9b6a-db391d1f98b9.png)

**Comment by solvedDev** [comment]
So, this issue is specific to projects created with bridge. v0.12.2 and below. Projects created with the latest pre-releases are *not* affected.

**Why does it happen?**
bridge. by default registered the client_data module for the scripting API inside your manifest.json file even if you do not make use of scripting. That was obviously a bad design choice and therefor corrected inside the bridge. v0.13.0 pre-releases. You now have to click a toggle inside the project creation window to register client_data, it's by default not registered.

**How can you fix it for already created projects?**
Open the manifest.json file of your addon with bridge. and open the "modules" JSON node. Click on the second entry ("1") and delete it. Save the file.
