### ISSUE TITLE
MacOS download

### ISSUE THREAD

**Issue by bufbuBSE** [solvedDev/bridge.#72]
**Summary**
This isn't really a feature I just can't seem to find the mac version of this program. There are issues related to it as if people have it, so how do I get it?

**Comment by solvedDev** [comment]
The first steps for support have been made (with some yet to come) but I won't provide a Mac build alongside the win build in the near future because I simply don't have a computer with an Unix operating system. You can compile your own build by running "npm i" and then "npm run build" inside the downloaded source code.

**Comment by solvedDev** [comment]
Compiling an own build is also how others got it btw. Requires installation of NodeJS

**Comment by Lancelotbronner** [comment]
Hi I built it for mac, but it seemed to crash on the .dmg creation. I replaced it with a .pkg instead and the build now produces the application. However, it cannot be opened:

Process:               bridge [10442]
Path:                  /Users/USER/*/bridge.app/Contents/MacOS/bridge
Identifier:            solved.editor.bridge
Version:               0.13.8 (0.13.8)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           bridge [10442]
User ID:               501

Date/Time:             2019-09-26 08:54:04.659 -0400
OS Version:            Mac OS X 10.15 (19A573a)
Report Version:        12
Anonymous UUID:        5192AAFF-B699-63EF-FE54-E7094C5E21BC

Sleep/Wake UUID:       497A8F88-3133-4892-B10B-0D17D0D91AFD

Time Awake Since Boot: 43000 seconds
Time Since Wake:       5100 seconds

System Integrity Protection: enabled

Crashed Thread:        9  Chrome_IOThread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [10442]

Thread 0:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x000000010a50c630 0x108a31000 + 28161584
1   com.github.Electron.framework 	0x000000010a2989fe 0x108a31000 + 25590270
2   com.github.Electron.framework 	0x000000010a296a44 0x108a31000 + 25582148
3   com.github.Electron.framework 	0x000000010a6e8eb7 0x108a31000 + 30113463
4   com.github.Electron.framework 	0x000000010a296206 0x108a31000 + 25580038
5   com.github.Electron.framework 	0x000000010a298e22 0x108a31000 + 25591330
6   com.github.Electron.framework 	0x000000010a2947d6 0x108a31000 + 25573334
7   com.github.Electron.framework 	0x000000010a1694c5 0x108a31000 + 24347845
8   com.github.Electron.framework 	0x000000010a1690b1 0x108a31000 + 24346801
9   com.github.Electron.framework 	0x000000010c4fc7f0 0x108a31000 + 61650928
10  com.github.Electron.framework 	0x00000001093f5cc4 0x108a31000 + 10243268
11  com.github.Electron.framework 	0x0000000108a33114 AtomMain + 84
12  solved.editor.bridge          	0x00000001089fba10 0x1089fa000 + 6672
13  libdyld.dylib                 	0x00007fff703c8405 start + 1

**Comment by solvedDev** [comment]
@Lancelotbronner Please open a new issue on your crash. Helps keeping things organized

**Comment by YOYITsM3M8** [comment]
How do I start Mac build?

**Comment by solvedDev** [comment]
The latest bridge. version comes with Mac builds by default; closing issue.
