### ISSUE TITLE
[BUG] Manifest has a parsing error

### ISSUE THREAD

**Issue by xWhoseManz** [solvedDev/bridge.#84]
After I create a behavior or resource pack and open Minecraft, it shows a parsing error when attempting to apply the pack to a new world. The error states the uuid of the pack as 00000000-0000-0000-000000000000 and the version as 0.0.0 and also says that the "format version is invalid".

Please tell me if I am doing anything wrong. I am using bridge. v0.13.9

**Comment by solvedDev** [comment]
@xWhoseManz Thanks for the report! We've been discussing the problem on our bridge. Discord server and came to the conclusion that the manifest.json format version number is the problem. You can manually set it to 1 (instead of 2) to fix this issue for Minecraft 1.12. On Minecraft 1.13, no change is required. 

I am going to change the format version number back to 1 for new manifests until Minecraft 1.13 releases officially

**Comment by xWhoseManz** [comment]
@solvedDev It worked. Thanks for the help!

**Comment by solvedDev** [comment]
You're welcome :)
